spring.application.name=Unifyx
spring.datasource.url=jdbc:mysql://localhost:3306/unifyxproject
spring.datasource.username=root
spring.datasource.password=kankubaa
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
server.address=0.0.0.0
server.port=8080
cloudinary.cloud-name=dhm6tu4us
cloudinary.api-key=689583417732242
cloudinary.api-secret=-nGM3NAjOhGbOr97D_38Ga5fT1U

